### ISSUE TITLE
ClassNotFoundException "java.util.Base64" Moto E4 device

### ISSUE THREAD

**Issue by dhiogoboza** [rubenochiavone/rastreio-java#3]
Hi, when I run my application in a Moto E4 real device a crash happens when the events area fetched, here are the logs:

```
2020-02-22 16:16:45.610 1354-1767/com.db.rastreioshare E/DataManager: Error retrieving package event: LB667176875SE
    java.lang.NoClassDefFoundError: rastreio.Magic
        at rastreio.Rastreio.newRequest(Rastreio.java:143)
        at rastreio.Rastreio.trackSync(Rastreio.java:121)
        at com.db.rastreioshare.manager.DataManager.updatePackageEvents(DataManager.java:532)
        at com.db.rastreioshare.manager.DataManager.access$100(DataManager.java:41)
        at com.db.rastreioshare.manager.DataManager$UpdatePackagesEventsTask.doInBackground(DataManager.java:93)
        at com.db.rastreioshare.manager.DataManager$UpdatePackagesEventsTask.doInBackground(DataManager.java:80)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;
        at rastreio.Magic.<clinit>(Magic.java:7)
        at rastreio.Rastreio.newRequest(Rastreio.java:143)
        at rastreio.Rastreio.trackSync(Rastreio.java:121)
        at com.db.rastreioshare.manager.DataManager.updatePackageEvents(DataManager.java:532)
        at com.db.rastreioshare.manager.DataManager.updatePackageEventSync(DataManager.java:504)
        at com.db.rastreioshare.manager.DataManager.access$000(DataManager.java:41)
        at com.db.rastreioshare.manager.DataManager$UpdatePackagesForGroupTask.doInBackground(DataManager.java:64)
        at com.db.rastreioshare.manager.DataManager$UpdatePackagesForGroupTask.doInBackground(DataManager.java:61)
        at android.os.AsyncTask$2.call(AsyncTask.java:305) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.Base64" on path: DexPathList[[zip file "/data/app/com.db.rastreioshare-2/base.apk"],nativeLibraryDirectories=[/data/app/com.db.rastreioshare-2/lib/arm, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at rastreio.Magic.<clinit>(Magic.java:7) 
        at rastreio.Rastreio.newRequest(Rastreio.java:143) 
        at rastreio.Rastreio.trackSync(Rastreio.java:121) 
        at com.db.rastreioshare.manager.DataManager.updatePackageEvents(DataManager.java:532) 
        at com.db.rastreioshare.manager.DataManager.updatePackageEventSync(DataManager.java:504) 
        at com.db.rastreioshare.manager.DataManager.access$000(DataManager.java:41) 
        at com.db.rastreioshare.manager.DataManager$UpdatePackagesForGroupTask.doInBackground(DataManager.java:64) 
        at com.db.rastreioshare.manager.DataManager$UpdatePackagesForGroupTask.doInBackground(DataManager.java:61) 
        at android.os.AsyncTask$2.call(AsyncTask.java:305) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
```

In android the substitute to this class is https://developer.android.com/reference/android/util/Base64.html.

**Comment by rubenochiavone** [comment]
Sorry for the inconvenience. A `base64` decoder class is not mandatory for the project. Since Android platform does not support` java.util.Base64` I will remove it altogether. Stay tuned for a new release.

**Comment by rubenochiavone** [comment]
Fixed it on `1.0.2` (35fd48ee1afefed493fd2f11888c78cf69bea5f7), please check it. :rocket:

Thank you for the bug report. :bug:

**Comment by dhiogoboza** [comment]
Thanks, I will test and report.

**Comment by dhiogoboza** [comment]
The new version works fine! Thanks!
